### PR TITLE
Project updates

### PR DESCRIPTION
**Pull request by akhtariali**
Updated projectlist and votebar components (also small changes on navbar icons).

### CODE REVIEW

**Comment by amdp** [comment]
Ali, I cannot approve. 1 You should never create old and new files, just push the new one with edits otherwise it's a mess. 2 Please add the modal in projectlist, not in home, otherwise the projectlist won't work in other situations.

**Comment by akhtariali** [comment]
1. I'll remove the old ones as soon as you approve the new changes, and we
make sure that we're not going to make any more changes. Until then, I
think it's better to keep the old components as a reference or in cases
that we want to revert the changes.
2. I moved the modal to projectlist.vue.

If you approve the changes, let me know so I remove the old components.

Il giorno mar 24 set 2019 alle ore 18:12 Alessandro Merletti de Palo <
notifications@github.com> ha scritto:

**Comment by amdp** [comment]
remove all xxxold

Thank you,
Alessandro Merletti De Palo
https://amdp.me

**Comment by amdp** [comment]
Ali, you edited the votebar too much.
That way we won't have the userbar and the proptype based votebar, so we
won't see any comments.
You shouldn't delete what you don't understand!!

Thank you,
Alessandro Merletti De Palo
https://amdp.me

**Comment by amdp** [comment]
It is mandatory that you see the authorized section. Edit the password in
the database and try to get in :)

Thank you,
Alessandro Merletti De Palo
https://amdp.me

**Pull request merged**
