### PR TITLE
Nav Updated

### PR DESCRIPTION
**Pull request by akhtariali**
The primary change:
- Updated navbar and made it responsive (check navbar.vue component)

Secondary changes:
- Added flex-box to the default layout (check default.vue layout)
- Added page-header and page-container classes to pages to make them responsive
- Removed `font-weight: 200` from `a:hover` styles

### CODE REVIEW

**Comment by amdp** [comment]
Very good!
On monday, please move the style scoped in any page into the css please
note that "navbarrow" has been changed to "main"

Thank you,
Alessandro Merletti De Palo
https://amdp.me

**Comment by amdp** [comment]
sent this to discord:

Ok, pull the merge, you'll see now the distance from the navbar has been
eliminated and everything is too high.The navbar menu is too bold as well
as the login.
So:
1 please, avoid style scoped, otherwise we'll go crazy finding where some
bootstrap class has been changed affecting stuff somewhere, everything
should be in coo.css2 less bold menu3 navbarrow => main or mainrow and fix
the distance from top of the page (it is too much close to the navbar)
great job!

Thank you,
Alessandro Merletti De Palo
https://amdp.me

Thank you,
Alessandro Merletti De Palo
https://amdp.me

**Comment by amdp** [comment]
you can also see your changes on phi.cooperacy.org now

Thank you,
Alessandro Merletti De Palo
https://amdp.me

**Comment by akhtariali** [comment]
Cool!

Il giorno gio 19 set 2019 alle ore 10:28 Alessandro Merletti de Palo <
notifications@github.com> ha scritto:

> you can also see your changes on phi.cooperacy.org now
>
> Thank you,
> Alessandro Merletti De Palo
> https://amdp.me
>
>
> On Thu, Sep 19, 2019 at 7:52 AM Alessandro Merletti De Palo <

**Pull request merged**
